// Geometry and palette of logo.mem - generated by tools/gen_logo.py, do not edit.
`ifndef LOGO_VH
`define LOGO_VH
`define LOGO_W 240
`define LOGO_H 55
`define LOGO_PAL1 24'hE31E25
`define LOGO_PAL2 24'h7E7D7D
`define LOGO_PAL3 24'hF18E92
`endif
