# Define the top module and file list
TOP_MODULE = top_module
FILE_LIST = filelist.txt

# Define Verilator commands
VERILATOR = verilator
VFLAGS = --cc --exe --build
CFLAGS = --top-module $(TOP_MODULE)

# Default target: compile and run
all: sim

# Simulation target
sim: $(FILE_LIST)
    $(VERILATOR) $(VFLAGS) $(CFLAGS) -f $(FILE_LIST)
    ./obj_dir/V$(TOP_MODULE)

# Clean target
clean:
    rm -rf obj_dir
    rm -f *.o *.d *.mk

.PHONY: all clean sim
