(part "H1102NL"
    (packageRef "SOIC127P940X597-16N")
    (interface
        (port "1" (symbPinId 1) (portName "TD+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "CT_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "TD-") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC_1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NC_2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "RD+") (portType INOUT))
        (port "7" (symbPinId 7) (portName "CT_2") (portType INOUT))
        (port "8" (symbPinId 8) (portName "RD-") (portType INOUT))
        (port "9" (symbPinId 9) (portName "RX-") (portType INOUT))
        (port "10" (symbPinId 10) (portName "NC_3") (portType INOUT))
        (port "11" (symbPinId 11) (portName "RX+") (portType INOUT))
        (port "12" (symbPinId 12) (portName "NC_4") (portType INOUT))
        (port "13" (symbPinId 13) (portName "NC_5") (portType INOUT))
        (port "14" (symbPinId 14) (portName "TX-") (portType INOUT))
        (port "15" (symbPinId 15) (portName "NC_6") (portType INOUT))
        (port "16" (symbPinId 16) (portName "TX+") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "152")
    (property "Mouser_Part_Number" "673-H1102NL")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Pulse-Electronics/H1102NL?qs=EKu32SdDin%2FHU33L94JZxw%3D%3D")
    (property "Manufacturer_Name" "Yageo Group")
    (property "Manufacturer_Part_Number" "H1102NL")
    (property "Description" "PULSE ELECTRONICS - H1102NL - TRANSFORMER, 1:1, 1PORT, 100BASE-TX, SMT")
    (property "Datasheet_Link" "https://productfinder.pulseeng.com/products/datasheets/h1102nl.pdf")
    (property "symbolName1" "H1102NL")
)
