# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/constrs/RASPMO.xdc

# IP: /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/ip/Video_clk/Video_clk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Video_clk || ORIG_REF_NAME==Video_clk} -quiet] -quiet
