# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/media/tobiw/LocalData/Data/RASentinel/RASPMO/vivado/RASPMO.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_msg_config  -id {HDL 9-3116}  -string {{CRITICAL WARNING: [HDL 9-3116] 'indexed name' is not a type [E:/Xilinx/Artix-7/Workspace-XC7A100T-DDR3-Wukong/08_1_hdmi_output_test/HDMI_output_test.srcs/sources_1/imports/src/TMDS_Encoder.vhd:90]}}  -suppress 
set_msg_config  -id {[Synth 8-7080]}  -severity {WARNING}  -new_severity {INFO} 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /media/tobiw/LocalData/Data/RASentinel/RASPMO/vivado/RASPMO.cache/wt [current_project]
set_property parent.project_path /media/tobiw/LocalData/Data/RASentinel/RASPMO/vivado/RASPMO.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /media/tobiw/LocalData/Data/RASentinel/RASPMO/vivado/RASPMO.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/adc_sequencer.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/fft/bimpy.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/bin2bcd.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/fft/bitreverse.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/fft/butterfly.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/fft/convround.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/cordic_vec.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/df_amp.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/dp_ram.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/fft/fftmain.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/fft/fftstage.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/freqmap.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/hdmi_clk.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/fft/hwbfly.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/iq_balance.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/fft/laststage.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/link_supervisor.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/fft/logfn.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/fft/longbimpy.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/lvds_rx_new.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/midmap.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/pane_overlay.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/polar_view.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/fft/qtrstage.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/ramp_checker.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/sample_cdc.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/scope_view.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/video_define.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/screen.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/waterfall_mem.v
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/top.v
}
read_vhdl -library xil_defaultlib {
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/hdmi/SyncAsync.vhd
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/hdmi/SyncAsyncReset.vhd
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/hdmi/ClockGen.vhd
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/hdmi/DVI_Constants.vhd
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/hdmi/OutputSERDES.vhd
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/hdmi/TMDS_Encoder.vhd
  /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/hdmi/rgb2dvi.vhd
}
read_ip -quiet /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/ip/Video_clk/Video_clk.xci
set_property used_in_implementation false [get_files -all /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/ip/Video_clk/Video_clk_board.xdc]
set_property used_in_implementation false [get_files -all /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/ip/Video_clk/Video_clk.xdc]
set_property used_in_implementation false [get_files -all /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/ip/Video_clk/Video_clk_late.xdc]
set_property used_in_implementation false [get_files -all /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/sources/ip/Video_clk/Video_clk_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/constrs/RASPMO.xdc
set_property used_in_implementation false [get_files /media/tobiw/LocalData/Data/RASentinel/RASPMO/rtl/constrs/RASPMO.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /media/tobiw/LocalData/Data/RASentinel/RASPMO/vivado/RASPMO.srcs/utils_1/imports/synth_1/top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7a100tcsg324-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
