(part "DS90LV028AQDQFRQ1"
    (packageRef "SON50P200X200X80-8N")
    (interface
        (port "1" (symbPinId 1) (portName "RIN1-") (portType INOUT))
        (port "2" (symbPinId 2) (portName "RIN1+") (portType INOUT))
        (port "3" (symbPinId 3) (portName "RIN2+") (portType INOUT))
        (port "4" (symbPinId 4) (portName "RIN2-") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND") (portType INOUT))
        (port "6" (symbPinId 6) (portName "ROUT2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "ROUT1") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VCC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-S90LV028AQDQFRQ1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/DS90LV028AQDQFRQ1?qs=BJlw7L4Cy79pzlV0%2FL5zww%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "DS90LV028AQDQFRQ1")
    (property "Description" "LVDS Driver 5-Pin SOT-23 T/R")
    (property "Datasheet_Link" "https://www.ti.com/lit/ds/symlink/ds90lv028a-q1.pdf?ts=1621932347476&ref_url=https%253A%252F%252Fwww.ti.com%252Fstore%252Fti%252Fen%252Fp%252Fproduct%252F%253Fp%253DDS90LV028AQDQFRQ1")
    (property "symbolName1" "DS90LV028AQDQFRQ1")
)
